### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by kerimli911** [Dr-Noob/MADFUT22_Hack#1]
Please fix this problem. I hack madfut with your tool. Thank you its worked. But Xabi Alonso SBC card no added. Every card unlocked. But only one card ( XabibAlonso SBC) locked. Please help me

**Comment by Dr-Noob** [comment]
Yeah, I know it was outdated. I just updated it, so it should work now!

Closing.

**Comment by kerimli911** [comment]
Thank you ♥️ You are BOSS 👑
--
Android için Mail.ru uygulamasından gönderildi Perşembe, 23 Aralık 2021, 01:48ÖS +04:00 gönderen: Dr-Noob  ***@***.*** :

**Comment by kerimli911** [comment]
Happy New Year Dr Noob ♥️
Do you have new script for Madfut?
--
Android için Mail.ru uygulamasından gönderildi Perşembe, 23 Aralık 2021, 01:48ÖS +04:00 gönderen: Dr-Noob  ***@***.*** :
