### ISSUE TITLE
Encrypt/Decrypt issue with non UTF-8 characters

### ISSUE THREAD

**Issue by alexmolprive** [Dr-Noob/MADFUT22_Hack#10]
Hi, I've been playing with your scripts, first of all, your tool is fantastic.
Unfortunately we have an issue with encrypting/decrypting on windows machines. 
That is probably why you excluded sbcGroups from your scripts.
It works good when you execute the scripts on a linux machine, but when doing it on windows, we run into codec errors.
Do you have any idea how to change the encodings so we can encrypt properly on windows (with emojis)

**Comment by Dr-Noob** [comment]
Yes, there is an issue with the decrypt/encrypt scripts with non UTF-8 characters, but this is not related to Linux or Windows. 

I have no intention to fix it, as everything works without it, except for specific things like emojis and this stuff. If anybody finds a way to fix it, pull requests are welcomed. 

Closing
