### ISSUE TITLE
could you make it easier for windows

### ISSUE THREAD

**Issue by UltimateBoi** [Dr-Noob/MADFUT22_Hack#11]
make one that does it on windows by just putting your mainactivity.xml to the folder

**Comment by UltimateBoi** [comment]
![image](https://user-images.githubusercontent.com/63293118/152696616-6103fec3-7ce2-420d-80b6-06d95d759fbb.png)
also this

**Comment by UltimateBoi** [comment]
sorted it ok byee

**Comment by ghost** [comment]
How did you fix it?

**Comment by UltimateBoi** [comment]
just removed it or somethiung

**Comment by alexmolprive** [comment]
You can remove the if statement to decrypt everything. But on windows you also managed to ecrypt it again?
