### ISSUE TITLE
Im now 80% sure that Encrypt and Decrypt dont work

### ISSUE THREAD

**Issue by UltimateBoi** [Dr-Noob/MADFUT22_Hack#14]
When i decrypt, there is no coins value anymore... I think its broken. Please fix

**Comment by UltimateBoi** [comment]
Also changing the coins amount in the madfut22.py just bugs it out a lot. Just crashes madfut even if i only add 1 more

**Comment by alexmolprive** [comment]
Decrypting and encrypting works fine. It might be your environment that is bugging.

**Comment by Dr-Noob** [comment]
@UltimateBoi You have posted so many things in the last few days. This may be easily considered as spam, so please, do not open an issue for asking a question. If you are sure you found a bug, please provide a concise explanation and instructions on how to reproduce it. Also, I remind you this: https://github.com/Dr-Noob/MADFUT22_Hack/issues/8#issuecomment-1024866634. It's good that you do some experiments with the script and all this stuff, but please do not post them.

If you keep posting stuff without control I will have no other option but to block you...

Closing

**Comment by UltimateBoi** [comment]
> Decrypting and encrypting works fine. It might be your environment that is bugging.

wdym.
ive tried like 1000 times and each time it is the same

**Comment by UltimateBoi** [comment]
Anywhay basicaly its just rlly bugy for windows ig

**Comment by alexmolprive** [comment]
There is just not that much bugy about the supplied scripts from Dr-Noob.
You need a bit of development knowledge to understand the situation.

I've been playing with the scripts and adjusted it to my needs. That is what you need to do, understand the code and adjust where needed. That is how software works.

**Comment by UltimateBoi** [comment]
Yes and so do i although mainly in java but still it is probably just madfut being terrible.

**Comment by UltimateBoi** [comment]
If you want to help me though, please friend me on discord: Coder_Ultimate#4100

Thanks
