### ISSUE TITLE
Decryption/encryption

### ISSUE THREAD

**Issue by jaylonwiggya** [Dr-Noob/MADFUT22_Hack#15]
Doesn't decrypt the whole file

**Comment by jaylonwiggya** [comment]
It misses the saved packs sadly that's what I'm using it for

**Comment by jaylonwiggya** [comment]
If you could fix it it'll be wonderful

**Comment by jaylonwiggya** [comment]
@Dr-Noob

**Comment by Dr-Noob** [comment]
I know, see commit d76d1231319b34b5ae9e57800e621469a3a241e2. I have no intention to fix it myself, but happy to include a fix if anyone finds it.
