### ISSUE TITLE
OS Matter?

### ISSUE THREAD

**Issue by UltimateBoi** [Dr-Noob/MADFUT22_Hack#16]
Does the OS matter,
would it work even if I'm on windows 11 for example (def not mac tho ew)

Just a general question

**Comment by Dr-Noob** [comment]
Yes, the OS matter, see the third dot in [the limitations section in the README](https://github.com/Dr-Noob/MADFUT22_Hack#limitations). The script may also work on other platforms but there is no guarantee for that.

**Comment by UltimateBoi** [comment]
> Yes, the OS matter, see the third dot in [the limitations section in the README](https://github.com/Dr-Noob/MADFUT22_Hack#limitations). The script may also work on other platforms but there is no guarantee for that.

Ok thank you.
