### ISSUE TITLE
[REQUEST] Tools

### ISSUE THREAD

**Issue by UltimateBoi** [Dr-Noob/MADFUT22_Hack#17]
So basically could you make a function that grabs every single pack id in the game, like the format of this: bf_94_special or like this: bf_nine_special

Thanks for reading and would be rlly nice if you could do this!

**Comment by Dr-Noob** [comment]
There is no way to know which packs are available in the game just by reading the .xml file since it only contains the packs that you have. Maybe if you reverse engineer some other file or the code itself there is a way of doing so, but I will not work in such a feature. 

Closing.
