### ISSUE TITLE
Trade not working

### ISSUE THREAD

**Issue by kerimli911** [Dr-Noob/MADFUT22_Hack#3]
after installation, trade not working

**Comment by Dr-Noob** [comment]
The trade may not work, not because of the script, but because the device is rooted.

**Comment by kerimli911** [comment]
My old mainactivity.xml file support trading. But new cracked file don't support trading. Only loop screen ![Screenshot_2022-01-23-13-21-43-223_com.madfut.madfut22.jpg](https://user-images.githubusercontent.com/96395537/150672209-a89ae8c9-46e8-4904-831c-ada2da83d8ae.jpg)

**Comment by Dr-Noob** [comment]
Yeah, I just tried it, and happened to me as well. It just takes time, but it eventually finds someone. If you trade with a friend it should find it instantly, I guess?

**Comment by kerimli911** [comment]
Yes friend it should find it instantly. But random trading not working. I hope you fix this bug ♥️♥️
--
Android için Mail.ru uygulamasından gönderildi Pazar, 23 Ocak 2022, 01:27ÖS +04:00 gönderen: Dr-Noob  ***@***.*** :

**Comment by Dr-Noob** [comment]
I would not expect it to happen soon, as it may be a bug in the game itself, not in the script

**Comment by IchNukeDichWeg** [comment]
There apprently is a shadow ban for Radom trading when u have more then 98% but trading with friends should work

**Comment by Dr-Noob** [comment]
> There apprently is a shadow ban for Radom trading when u have more then 98% but trading with friends should work

It might be a good explanation. Is it just your impression, or do you have any reference that could confirm this?
