### ISSUE TITLE
Hey DrNoob  

### ISSUE THREAD

**Issue by user67754321234567890** [Dr-Noob/MADFUT22_Hack#9]
hello Dr Noob i cant seem to open a crack.sh or find a mainactivity because i dont know how to any of them so please please and please may you assist me through its installtion by contacting me on any social or even here

**Comment by Dr-Noob** [comment]
Just follow the instructions in the README, and if you have any doubt or problem you can ask it here, but please **be specific**.

**Comment by user67754321234567890** [comment]
Hey i understand and i have fully read it but when it comes to open crack.sh and set auser and whats after i don't know how to do it
Thanks alot for reaching out I appreciate your efforts much Respect

**Comment by Dr-Noob** [comment]
1. Connect the phone to the computer and make sure that adb works fine (you can check with `adb shell`, you should get a shell in your phone).
2. Run `adb shell "su -c ls -l /data/data/com.madfut.madfut22/shared_prefs"`. This will print a list of files and the owner of such files. The owner should be something like `u0_aXXX` where `XXX` is a number.
3. Open crack.sh (with a text editor, e.g., gedit). Change the first line (`auser=""`) and write the user you just found in the previous step (you should end with something like `auser="u0_aXXX"`
4. Run crack.sh (`./crach.sh`)

If anything does not work, please specify in which step you got stuck.

**Comment by user67754321234567890** [comment]
Hey again the only issue left is when opening the crack.sh and after changing the auser how do i save it and run the file please help and thanks

**Comment by user67754321234567890** [comment]
It says I don't have permission to save it

**Comment by user67754321234567890** [comment]
Dr help me please

**Comment by UltimateBoi** [comment]
ye also what do you do if ur doing it in a emulator?

**Comment by Dr-Noob** [comment]
> Hey again the only issue left is when opening the crack.sh and after changing the auser how do i save it and run the file please help and thanks

Unfortunately, this is not a Linux tutorial, but a page for reporting bugs or comments regarding this software.

Closing

**Comment by Dr-Noob** [comment]
> ye also what do you do if ur doing it in a emulator?

It should not be different from running it on a real device.
